version: '3.9'

services:

  # MongoDB services
  mongo_db:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - 2717:27017

  # Node API service
  api:
    build: .
    restart: always
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGO_URI: mongodb://mongo_db:27017
      DB_NAME: dockerise
    ports:
      - 4000:3000
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
